# Generated by Django 5.2.4 on 2025-07-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='texto',
        ),
        migrations.AddField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=100),
        ),
        migrations.AddField(
            model_name='comentario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
